require: rubocop-rails
AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - spec/spec_helper.rb
    - Gemfile
    - bin/*
Rails:
  Enabled: true
Documentation:
    Enabled: false
Metrics/LineLength:
  Max: 120
