default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: api_development

test:
  <<: *default
  database: api_test

production:
  <<: *default
  database: api_production
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
